### ISSUE TITLE
support document specific links

### ISSUE THREAD

**Issue by freeman-lab** [freeman-lab/minidocs#17]
It'd be nice if we could add to each document an optional link (e.g. to an external website, or to a github repo), which would then be displayed above the contents pane. Could be specified in `contents.json` if we support extra fields like:

```
{
   'about': {file: 'about.md', link: 'https://mywebsite.com'}
   'example': {file: 'example.md', link: 'https://anotherwebsite.com'}
}
```

But it'd be nice to keep supporting the simpler case of mapping keys to markdown files, could be supported by doing some simple type checking on the value (i.e. if string, construct an object with that string as the file).

**Comment by freeman-lab** [comment]
cc @sethvincent

**Comment by fraserxu** [comment]
Love the idea! I was thinking about this before as well but forgot to follow up here.

There's package on npm called [yfm](https://www.npmjs.com/package/yfm) which can be used to parse `yml` content from a markdown file. I think this is what Github pages use for Jekyll. 

This could allow us to define other **meta** information like `last_update_date`, `link`, `publish_by` and more other stuff. Plus this is what people already did in there markdown documentation.

```Markdown
---
title: YAML Front matter
description: This is a page
---

my documentation
```

**Comment by sethvincent** [comment]
I've got it working with revisions to contents.json like this:

```js
'overview': {
    'about': {
      file: 'about.md',
      link: 'http://github.com/freeman-lab/minidocs'
    }
  },
```

And making it render so there's a `source` link above the title:

![screen shot 2016-04-21 at 5 27 15 pm](https://cloud.githubusercontent.com/assets/164214/14728066/7e0685c0-07e6-11e6-8790-d30aeb25b763.png)

There might be better placement. Also not sure if source is the best word.

Work in progress in the [document-links](https://github.com/freeman-lab/minidocs/tree/document-links) branch.

**Comment by sethvincent** [comment]
@fraserxu Having support for yaml could be handy. I'm not sure how many other variables we might want to introduce other than `link`.
