### ISSUE TITLE
cli tool: option for generating full index files

### ISSUE THREAD

**Issue by sethvincent** [freeman-lab/minidocs#22]
It would be convenient if the command-line tool could generate full html files for each of the pages.

This would be particularly useful for supporting pathnames (#19) on github pages.

If we have an html file for each page, it would make supporting pathnames using html5 pushstate on github pages possible.

This is because github pages can't send a 200 request on the first request unless there's an html file at the given pathname.

This would be pretty easy to add, and would just introduce a `--html` option (or something like that) to the command-line that's `false` by default.

**Comment by fraserxu** [comment]
👍  This could really help for users with JavaScript disabled. 

I'm also planning to build a simple authenticate layer on top of the generated doc to make it support protected content from private Github repo. This could definitely make things easier.

**Comment by sethvincent** [comment]
this made it in via #25 🎉
