### ISSUE TITLE
permalink requires server rendering

### ISSUE THREAD

**Issue by clkao** [freeman-lab/minidocs#26]
It seems http://minidocs-example.surge.sh/pig won't work, which is linked from the index at http://minidocs-example.surge.sh

The page needs to be either server-side rendered or captured with 404 and rerouted to the app.  Or we can just use url hash.

**Comment by sethvincent** [comment]
Oh yeah, it should be re-deployed with a 200.html file: https://surge.sh/help/adding-a-200-page-for-client-side-routing

The cli tool can generate that as part of a static site build, or we can just copy the existing index.html to 200.html.

**Comment by freeman-lab** [comment]
@clkao thanks for catching! fixed in https://github.com/freeman-lab/minidocs/commit/6e59c634460d43b2ba6f874531b55f3c610bedfc, and redeployed to surge

**Comment by clkao** [comment]
yay!  I think it will need to be 404.html for publishing on github pages though, and it should be noted somewhere in the docs

**Comment by sethvincent** [comment]
It looks like the downside of using `404.html` on github pages is that it is sent with a 404 status code, which isn't ideal for things like search engine bots.

**Comment by clkao** [comment]
FTR 200.html support in gh-pages is tracked here: https://github.com/isaacs/github/issues/408

**Comment by sethvincent** [comment]
For now this is resolved. To deploy to github we can use the `--full-html` option and that works. But we should watch out for any new 200.html support on GitHub Pages as that will simplify things a lot.
