### ISSUE TITLE
pages got canonicalized on gh-pages and break links

### ISSUE THREAD

**Issue by clkao** [freeman-lab/minidocs#30]
For example, the permalink `http://docs.dat-data.com/api` generated from the client app, will get canonicalized as `http://docs.dat-data.com/api/` when user reloads or visits the page directly.  This makes the logo and potentially links within markdown broken.

**Comment by sethvincent** [comment]
The basedir option in #33 resolved this. 🎉 Thanks @clkao for all the help debugging this!
