### ISSUE TITLE
mobile style improvements

### ISSUE THREAD

**Issue by sethvincent** [freeman-lab/minidocs#46]
Right now a minidocs site is mostly unusable on a mobile phone.

Minimal high-level changes needed to get reasonable usability when viewed on mobile device:

- put logo at top of page
- hide sidebar by default
- show menu button that when touched shows the menu

**Comment by freeman-lab** [comment]
Fixed by https://github.com/freeman-lab/minidocs/pull/48 right?

**Comment by sethvincent** [comment]
👍
