### ISSUE TITLE
Custom style option: Add user css after default css (instead of prepending it)

### ISSUE THREAD

**Issue by Kriesse** [freeman-lab/minidocs#62]
When using the custom style option, the custom css is prepended. This makes overwriting existing styles hard.
I suggest inserting any custom user styles after the default styles to allow overwriting without additional selectors and !important.

**Comment by sethvincent** [comment]
:+1: I'll check this out.

**Comment by karissa** [comment]
What's the status of this?

**Comment by sethvincent** [comment]
_Just_ merged a fix for this. If you want to try it out you can install minidocs with `npm i freeman-lab/minidocs`. 

I've already tested it against the dat docs.

I'll publish a new version after making sure everything works.

**Comment by sethvincent** [comment]
This should be fixed in v4.1.0. The current approach is that all css added by minidocs is in bundle.css, and the custom css file you add is in style.css, which is referenced in index.html after bundle.css.
