### ISSUE TITLE
Feature: Add TOC for page to Menu

### ISSUE THREAD

**Issue by joehand** [freeman-lab/minidocs#63]
@karissa suggested it'd be nice to have a TOC for the current page in the menu (similar to Read the Docs). It'd definitely be useful but may be a pretty big feature (especially if we do all the TOC levels + collapsing). 

What do y'all think of adding this feature? Maybe we could start with just the minimal TOC of h2 headers.

I did a quick [prototype here](https://github.com/joehand/minidocs/tree/add/toc) and tried to add some minimal styles:

<img width="1280" alt="screen shot 2016-08-25 at 11 18 07" src="https://cloud.githubusercontent.com/assets/684965/17980761/a3b9ce12-6ab5-11e6-9bf7-b24f2b7961be.png">

**Comment by sethvincent** [comment]
Looks like it would be useful for big pages. Going with just h2 headers might be a good idea.

**Comment by sethvincent** [comment]
closed by #68
