### ISSUE TITLE
Peer sheetify@5.1.0 wants insert-css@^1.0.0

### ISSUE THREAD

**Issue by YerkoPalma** [freeman-lab/minidocs#65]
I was installing a repo that depends on minidocs and I got this error while `npm install`ing

```
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package insert-css@0.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sheetify@5.1.0 wants insert-css@^1.0.0
```

The project doesn't use sheetify, just minidocs, so I saw you are [using `insert-css@^0.2.0`](https://github.com/freeman-lab/minidocs/blob/master/package.json#L55) and sheetify [peer depends on `insert-css@^1.0.0`](https://github.com/stackcss/sheetify/blob/master/package.json#L38). So just upgrading insert-css in package.json should fix that.

**Comment by sethvincent** [comment]
fixed this in v4.1.0! thanks for pointing it out.
